language: node_js

node_js:
  - 8
  - node

before_script:
  - npm install
  - npm install -g codecov

script:
  - npm run lint
  - npm run dtslint
  - npm run codecov-test

after_success:
  - codecov
